
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 01 21:31:14 CST 2018
//----------------------------------------------------

package operacionesaritmeticasarbolexc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 9;
  public static final int MENOS = 5;
  public static final int ENTERO = 8;
  public static final int POR = 6;
  public static final int DIVIDIDO = 7;
  public static final int EOF = 0;
  public static final int MAS = 4;
  public static final int PARIZQ = 2;
  public static final int error = 1;
  public static final int PARDER = 3;
}

